version: "3.3"

services:
    oraclDB:
        restart: always
        expose:
            - "1521"
        ports:
            - "1521:1521"
        environment:
            - ./oracle-environment
        image: container-registry.oracle.com/database/standard
        
    server:
        ports:
            - "8080:8080"
        expose:
            - "8080"
        links:
            - oraclDB
        image: rest_server
        
    client:
        ports:
            - "8081:8081"
        expose:
            - "8081"
        links:
            - server
        image: rest_client
        
    selenoid:
        network_mode: bridge
        image: aerokube/selenoid:latest-release
        volumes:
          - "./config_browser_selenoid:/etc/selenoid"
          - "./var/run/docker.sock:/var/run/docker.sock"
          - "./config_browser_selenoid/video:/opt/selenoid/video"
          - "./config_browser_selenoid/logs:/opt/selenoid/logs"
        environment:
          - OVERRIDE_VIDEO_OUTPUT_DIR=/path/to/config/video
        command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs"]
        expose:
            - "4444"
        ports:
            - "4444:4444"